table fct_voorraad
	lineageTag: 074b9ca6-316b-454b-a6a9-87adfca23055

	measure 'Totale voorraadwaarde' = SUM(fct_voorraad[voorraadwaarde])
		lineageTag: 74a51fba-760d-4e6d-b1f0-efcb7ea06fd4

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Voorraadwaarde label' = "€ " & FORMAT([Totale voorraadwaarde], "#,##0", "nl-NL") & ",-"
		lineageTag: fce9ec3d-0a07-4c08-a51d-e90480523bed

		changedProperty = IsHidden

	measure 'Voorraad flessen' = SUM(fct_voorraad[voorraad])
		formatString: 0
		lineageTag: e4275cff-74c4-40cf-a12e-e5cd2b3593c8

		changedProperty = IsHidden

	/// Winsorised vraag (2026-08-20, was gem_per_week_12w) - consistent met de dekking_weken-kolom in de mart. De ongecorrigeerde rates staan in [Vraag per week 12w]/[52w].
	measure 'Vraag per week' = SUM(fct_voorraad[vraag_per_week])
		lineageTag: 0c84e7fa-aa8c-4332-90a6-3a72259e19b7

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Weken dekking op EFFECTIEVE voorraad: (voorraad + in_bestelling - gereserveerd) / vraag per week. ZICHTBAAR sinds 2026-08-20: effectieve voorraad bestaat nu gevalideerd in de mart, afgeleid uit de ERP-orders en -inkoop. De oude definitie op ruwe voorraad negeerde gereserveerde en inkomende flessen in tegengestelde richtingen en was daarom verborgen - zie de mart-header van fct_voorraad_db voor de validatie.
	measure 'Dekking weken' = DIVIDE(SUM(fct_voorraad[effectieve_voorraad]), [Vraag per week])
		formatString: 0.0
		lineageTag: 17cf8434-5d54-4e38-9f94-8aa6b66de819

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Brutomarge = SUM(fct_voorraad[brutomarge_12m])
		lineageTag: 589330fa-725c-4415-9fc0-9dd676f630b7

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Omzet 12m' = SUM(fct_voorraad[omzet_12m])
		lineageTag: 5153112a-9d0e-4411-8085-7bf1d9fb28a0

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Brutomarge %' = DIVIDE([Brutomarge], [Omzet 12m])
		lineageTag: 0fd32d6d-56cf-4324-9f9a-4bdf27ee7576

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Aantal wijnen' = COUNTROWS(fct_voorraad)
		formatString: 0
		lineageTag: 6ff4bc7b-644c-4cd8-8864-1d4d2c6dd531

		changedProperty = IsHidden

	measure 'Voorraad flessen label' = FORMAT([Voorraad flessen], "#,##0", "nl-NL")
		lineageTag: cdc0020c-ca0b-48ff-8fa1-d1ac4e5369f5

		changedProperty = IsHidden

	measure 'Vraag per week label' = FORMAT([Vraag per week], "#,##0.0", "nl-NL")
		lineageTag: a11c59d0-ae16-445d-9f8e-8fbe2cd4c945

		changedProperty = IsHidden

	/// Nederlandse weergave van [Dekking weken]. Zichtbaar sinds 2026-08-20, samen met de basismeting - die rekent nu op effectieve voorraad.
	measure 'Dekking label' = FORMAT([Dekking weken], "0.0", "nl-NL") & " weken"
		lineageTag: ea9bedce-ca27-41ce-9842-17bdb0f8f322

		changedProperty = IsHidden

	measure 'Brutomarge label' = "€ " & FORMAT([Brutomarge], "#,##0", "nl-NL") & ",-"
		lineageTag: f75b011c-46d7-4ac4-aa5e-43da78532a44

		changedProperty = IsHidden

	measure 'Brutomarge % label' = FORMAT([Brutomarge %], "0.0%", "nl-NL")
		lineageTag: 7435fccf-f415-4ea8-9c81-5d0faf3d8ccb

		changedProperty = IsHidden

	measure 'Aantal wijnen label' = FORMAT([Aantal wijnen], "#,##0", "nl-NL")
		lineageTag: deb4e46c-290c-40e9-949a-21d83d6e70fb

	measure 'Vraag per week 12w' = SUM(fct_voorraad[gem_per_week_12w])
		lineageTag: ff0a3a2b-6414-4150-a0e5-451a1bc52c59

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Vraag per week 52w' = SUM(fct_voorraad[gem_per_week_52w])
		lineageTag: 0d697df5-9bfd-4c35-860f-8921627c5de1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// 8 weken op de winsorised rate (2026-08-20, was de kale 12w-rate).
	measure 'Verwachte vraag 8 weken' = ROUND([Vraag per week] * 8, 0)
		lineageTag: 6a1e2fbc-da16-4921-b7bc-271231accb09

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Vraag 8 weken label' = FORMAT([Verwachte vraag 8 weken], "#,##0", "nl-NL") & " flessen"
		lineageTag: b22bd444-5cdc-4e86-bf5d-b868b4054acf

	column product_id
		dataType: string
		lineageTag: f22072f5-7ef7-46c3-a644-f6e26ca36b87
		summarizeBy: none
		sourceColumn: product_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column product_naam
		dataType: string
		lineageTag: e099a7f7-2b75-45b4-bf3f-0b6a91b8266c
		summarizeBy: none
		sourceColumn: product_naam

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column artikelcode
		dataType: string
		lineageTag: 77406200-00af-4188-a33e-0428dfd72d08
		summarizeBy: none
		sourceColumn: artikelcode

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column leverancier
		dataType: string
		lineageTag: 3b35b13a-6c61-4290-85a5-79f20d5f6d01
		summarizeBy: none
		sourceColumn: leverancier

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column wijnhuis
		dataType: string
		lineageTag: 3f2e0ef6-a48a-422e-9ee7-aaa4f3fdd133
		summarizeBy: none
		sourceColumn: wijnhuis

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column crediteurnummer
		dataType: string
		lineageTag: ff3dc4b4-bc48-44ab-b82a-6ef1a961d848
		summarizeBy: none
		sourceColumn: crediteurnummer

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column voorraad
		dataType: double
		formatString: 0
		lineageTag: b6d0314c-4e5d-4904-8af6-6323994d2e75
		summarizeBy: sum
		sourceColumn: voorraad

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column kritische_voorraad
		dataType: int64
		formatString: 0
		lineageTag: 28abb434-df01-4a53-8abc-b528a253844a
		summarizeBy: sum
		sourceColumn: kritische_voorraad

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column inkoopprijs
		dataType: double
		lineageTag: 76a18927-d22e-4d67-a5e1-e952ca7fde34
		summarizeBy: sum
		sourceColumn: inkoopprijs

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column basisprijs
		dataType: double
		lineageTag: cce566bc-4062-4459-9920-f553519c63d0
		summarizeBy: sum
		sourceColumn: basisprijs

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column voorraadwaarde
		dataType: double
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 6cead012-256f-4f74-9f59-79d6be02ed0a
		summarizeBy: sum
		sourceColumn: voorraadwaarde

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column marge_pct_lijst
		dataType: double
		lineageTag: 7056fee9-634a-49e3-ab01-d2a5128788b5
		summarizeBy: sum
		sourceColumn: marge_pct_lijst

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column flessen_12w
		dataType: double
		lineageTag: 70ff2c8b-ac49-45bf-b00f-13562098e58e
		summarizeBy: sum
		sourceColumn: flessen_12w

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column flessen_52w
		dataType: double
		lineageTag: a687ebcd-e971-48fd-be3f-f2d2ca76414c
		summarizeBy: sum
		sourceColumn: flessen_52w

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column gem_per_week_12w
		dataType: double
		lineageTag: 9a379d8b-6eae-4d6d-98ca-b98bc33ebbac
		summarizeBy: sum
		sourceColumn: gem_per_week_12w

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column gem_per_week_52w
		dataType: double
		lineageTag: 8e2c67d5-b43b-4a08-a505-264afb785cb8
		summarizeBy: sum
		sourceColumn: gem_per_week_52w

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column gemiddeld_per_week_erp
		dataType: double
		formatString: 0
		lineageTag: ed0ddf9b-7da6-4619-9d10-d77d7f3e25a7
		summarizeBy: sum
		sourceColumn: gemiddeld_per_week_erp

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column lead_time_days
		dataType: int64
		formatString: 0
		lineageTag: fe3248f8-37b9-41c1-bb8d-936bd2ea4373
		summarizeBy: sum
		sourceColumn: lead_time_days

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column lead_time_is_default
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 4c190f62-d981-4a7c-87ac-b8479de51417
		summarizeBy: none
		sourceColumn: lead_time_is_default

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column eerste_verkoop
		dataType: dateTime
		formatString: Long Date
		lineageTag: 222dd9b9-ffc2-4ca2-a9d1-799ec718fead
		summarizeBy: none
		sourceColumn: eerste_verkoop

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column laatste_verkoop
		dataType: dateTime
		formatString: dd/mm/yy
		lineageTag: 7748732b-917d-4d55-a21e-8f5c36e08135
		summarizeBy: none
		sourceColumn: laatste_verkoop

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isCustom":true}

	column maanden_sinds_laatste_verkoop
		dataType: double
		lineageTag: d74bdae6-b04f-40ea-97f3-d260f9c28627
		summarizeBy: sum
		sourceColumn: maanden_sinds_laatste_verkoop

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column n_klanten
		dataType: int64
		formatString: 0
		lineageTag: 954dc332-35b2-451a-bffb-992751d0efbb
		summarizeBy: sum
		sourceColumn: n_klanten

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column n_orders
		dataType: int64
		formatString: 0
		lineageTag: 072b86fb-839f-4c8e-94b9-bbcf89aa4001
		summarizeBy: sum
		sourceColumn: n_orders

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column omzet_12m
		dataType: double
		lineageTag: 5cb8a642-1c8d-4dae-b6fe-31bb1b465067
		summarizeBy: sum
		sourceColumn: omzet_12m

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column kostprijs_12m
		dataType: double
		lineageTag: d6345498-45dd-46ab-992c-961b27a15bf0
		summarizeBy: sum
		sourceColumn: kostprijs_12m

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column brutomarge_12m
		dataType: double
		lineageTag: 94c6c94d-ec37-46cf-b2b9-4021813f8183
		summarizeBy: sum
		sourceColumn: brutomarge_12m

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column brutomarge_pct_12m
		dataType: double
		lineageTag: 2805c36e-fd9c-4e71-89d8-efb84d6c08e4
		summarizeBy: sum
		sourceColumn: brutomarge_pct_12m

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column omzet_rang_12m
		dataType: int64
		formatString: 0
		lineageTag: 15c5aea3-305c-470d-b53a-e5cc702fc61b
		summarizeBy: none
		sourceColumn: omzet_rang_12m

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column flessen_rang_12w
		dataType: int64
		formatString: 0
		lineageTag: 71c699aa-4ff0-43f8-9677-6e094fdab085
		summarizeBy: none
		sourceColumn: flessen_rang_12w

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column is_hardloper
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 49693ffd-7fb5-4623-9cc8-33ffb5600bdd
		summarizeBy: none
		sourceColumn: is_hardloper

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column is_top50_omzet
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 43b50920-a9ab-4ec4-9acc-03ba033960c4
		summarizeBy: none
		sourceColumn: is_top50_omzet

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column niet_verkocht_bucket
		dataType: string
		lineageTag: b3015436-7589-4656-ad91-6f65f4ab865f
		summarizeBy: none
		sourceColumn: niet_verkocht_bucket

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column is_slow_mover
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: a0765dcd-8fed-4105-82b0-123619e37fe4
		summarizeBy: none
		sourceColumn: is_slow_mover

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column is_collectiepost
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: ba8fdd91-3573-4d0d-9954-65c33dd9a4b3
		summarizeBy: none
		sourceColumn: is_collectiepost

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column snapshot_datum
		dataType: dateTime
		formatString: Long Date
		lineageTag: 216b53c1-0741-4b7c-bcec-600a8a277f47
		summarizeBy: none
		sourceColumn: snapshot_datum

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column grootste_order_12w
		dataType: int64
		formatString: 0
		lineageTag: a570b67b-ff88-4505-839d-e2603c6e4bc3
		summarizeBy: none
		sourceColumn: grootste_order_12w

		annotation SummarizationSetBy = User

	column vraag_geconcentreerd
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: f78a9f45-86ec-414f-aaae-820a9e03d24e
		summarizeBy: none
		sourceColumn: vraag_geconcentreerd

		annotation SummarizationSetBy = Automatic

	column gem_verkoopprijs_12m
		dataType: double
		lineageTag: d6317e27-a8fa-4d73-940c-a875a65d8620
		summarizeBy: none
		sourceColumn: gem_verkoopprijs_12m

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column n_prijzen
		dataType: int64
		formatString: 0
		lineageTag: d3972667-e5cc-453b-8b15-57c89caea424
		summarizeBy: none
		sourceColumn: n_prijzen

		annotation SummarizationSetBy = User

	column korting_vs_lijst_pct
		dataType: double
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 92da60b6-4dcd-4670-bb97-fb91498dae85
		summarizeBy: none
		sourceColumn: korting_vs_lijst_pct

		annotation SummarizationSetBy = User

	/// Unieke weergavenaam: product_naam is niet uniek (737 namen voor 740 producten). Voegt de artikelcode toe waar namen botsen, net als fct_klant[klant_label].
	column product_label =
			VAR Voorkomens =
			    CALCULATE(COUNTROWS(fct_voorraad), ALLEXCEPT(fct_voorraad, fct_voorraad[product_naam]))
			RETURN
			    IF(Voorkomens > 1,
			        fct_voorraad[product_naam] & " (" & fct_voorraad[artikelcode] & ")",
			        fct_voorraad[product_naam])
		dataType: string
		lineageTag: 02e98ce9-219a-43ab-921f-a75477bf100d
		summarizeBy: none

	/// 0 voor de dienstregels Accijns, Divers, Statiegeld, Transport, Vrachtkosten en Verzending (en voor de lege unknown-member rij), 1 voor echte producten. Kolom en geen measure: een kolomfilter werkt voor het groeperen en is dus grain-safe. Niet afleiden uit een lege artikelcode - Poujol Lacoste Blanc, Villa Blanche Chardonnay en Ruinart hebben er ook geen.
	column is_wijn =
			VAR N = fct_voorraad[product_naam]
			RETURN
			    IF(
			        ISBLANK(N) || N IN {"Accijns", "Divers", "Statiegeld", "Transport", "Vrachtkosten", "Verzending"},
			        0,
			        1
			    )
		dataType: int64
		lineageTag: 8874d6a7-b66a-4681-8724-923346849ba2
		summarizeBy: none

	/// Omzet in het vorige 12-maandsvenster, opgeteld uit fct_klant_product. Die mart heeft omzet_12m en omzet_vorige_12m als gekoppeld paar en het huidige venster sluit exact aan op fct_voorraad[omzet_12m]. SUMX over ALL() en geen CALCULATE: CALCULATE doet contexttransitie in een berekende kolom en maakt de kolom afhankelijk van de hele tabel, wat een circulaire afhankelijkheid geeft met de andere venster-kolommen.
	column omzet_vorige_12m =
			VAR Pid = fct_voorraad[product_id]
			RETURN
			    SUMX(
			        FILTER(ALL(fct_klant_product), fct_klant_product[product_id] = Pid),
			        fct_klant_product[omzet_vorige_12m]
			    )
		dataType: double
		lineageTag: 498e02ce-acb2-4aee-9e3d-b259b36fd968
		summarizeBy: sum

	column flessen_vorige_12m =
			VAR Pid = fct_voorraad[product_id]
			RETURN
			    SUMX(
			        FILTER(ALL(fct_klant_product), fct_klant_product[product_id] = Pid),
			        fct_klant_product[flessen_vorige_12m]
			    )
		dataType: double
		lineageTag: 8ad1cf22-d032-4c0a-8568-2cd1eb148fc7
		summarizeBy: sum

	/// Zakelijke klanten met omzet op deze wijn in het vorige venster. Zelfde afbakening als klanten_nu_zakelijk.
	column klanten_vorige_12m =
			VAR Pid = fct_voorraad[product_id]
			RETURN
			    COUNTROWS(
			        FILTER(
			            ALL(fct_klant_product),
			            fct_klant_product[product_id] = Pid
			                && fct_klant_product[is_zakelijk] = 1
			                && fct_klant_product[omzet_vorige_12m] > 0
			        )
			    )
		dataType: int64
		lineageTag: f60047d9-0e89-4017-94d5-c6ab2e354984
		summarizeBy: sum

	/// Hexkleur voor het groeicijfer op Productdetail. Een cardVisual kan zijn fontColor alleen datagestuurd maken via Aggregation(Min) over een kolom. Geen CALCULATE: dat geeft contexttransitie en circulaire afhankelijkheden tussen deze kolommen.
	column omzet_groei_kleur =
			VAR Nu = fct_voorraad[omzet_12m]
			VAR Vorig = fct_voorraad[omzet_vorige_12m]
			RETURN IF(ISBLANK(Vorig) || Vorig = 0 || Nu >= Vorig, "#1F9D55", "#CC3B2F")
		dataType: string
		lineageTag: f8486b43-fe7f-4ac3-8be6-682db3a2f1b9
		summarizeBy: none

	column flessen_groei_kleur =
			VAR Nu = fct_voorraad[flessen_52w]
			VAR Vorig = fct_voorraad[flessen_vorige_12m]
			RETURN IF(ISBLANK(Vorig) || Vorig = 0 || Nu >= Vorig, "#1F9D55", "#CC3B2F")
		dataType: string
		lineageTag: e03a70df-626b-4944-8ffd-b255e1161ccf
		summarizeBy: none

	column klanten_groei_kleur =
			VAR Nu = fct_voorraad[klanten_nu_zakelijk]
			VAR Vorig = fct_voorraad[klanten_vorige_12m]
			RETURN IF(ISBLANK(Vorig) || Vorig = 0 || Nu >= Vorig, "#1F9D55", "#CC3B2F")
		dataType: string
		lineageTag: 95ad3017-4428-4bc4-b64b-3c032eeee0da
		summarizeBy: none

	column prijs_groei_kleur =
			VAR NuPrijs = DIVIDE(fct_voorraad[omzet_12m], fct_voorraad[flessen_52w])
			VAR VorigPrijs = DIVIDE(fct_voorraad[omzet_vorige_12m], fct_voorraad[flessen_vorige_12m])
			RETURN IF(ISBLANK(VorigPrijs) || VorigPrijs = 0 || NuPrijs >= VorigPrijs, "#1F9D55", "#CC3B2F")
		dataType: string
		lineageTag: 6e1af692-ba18-4128-ad9e-6740da8069ba
		summarizeBy: none

	/// Zakelijke klanten met omzet op deze wijn in het huidige venster. Tegenhanger van klanten_vorige_12m, zodat de groei appels met appels vergelijkt. Niet fct_voorraad[n_klanten]: die telt alle klanten inclusief consumenten en telt ook regels zonder omzet mee.
	column klanten_nu_zakelijk =
			VAR Pid = fct_voorraad[product_id]
			RETURN
			    COUNTROWS(
			        FILTER(
			            ALL(fct_klant_product),
			            fct_klant_product[product_id] = Pid
			                && fct_klant_product[is_zakelijk] = 1
			                && fct_klant_product[omzet_12m] > 0
			        )
			    )
		dataType: int64
		lineageTag: b48156e1-d710-4171-814f-f4261deac488
		summarizeBy: sum

	/// Flessen op open verkooporders (status Nieuw - verwerken / Backorder). Afgeleid uit de ERP-database en exact gevalideerd tegen de voorraadpagina (48/48 producten). Klaargezette orders reserveren NIET - die voorraad is al afgeboekt.
	column gereserveerd
		dataType: double
		formatString: 0
		lineageTag: 531b4ba2-50b2-42e0-8174-f06210498ec8
		summarizeBy: sum
		sourceColumn: gereserveerd

	/// Flessen op verzonden, open inkooporders. Telt bewust alleen verzonden orders (d_send gezet) - concepten zijn een voornemen, geen inkomende voorraad. Wijkt daarmee bewust af van de ERP-pagina, die concepten inconsistent meetelt.
	column in_bestelling
		dataType: double
		formatString: 0
		lineageTag: e0c398c7-f8b6-4f32-b9b8-74e085bd50b6
		summarizeBy: sum
		sourceColumn: in_bestelling

	/// voorraad + in_bestelling - gereserveerd: wat er werkelijk te beloven valt. De basis voor dekking en voorraadstatus.
	column effectieve_voorraad
		dataType: double
		formatString: 0
		lineageTag: c5dc3084-7e11-43fb-aa44-bcb4cdbcd30d
		summarizeBy: sum
		sourceColumn: effectieve_voorraad

	/// Weken dekking op EFFECTIEVE voorraad (effectieve_voorraad / gem_per_week_12w). NULL waar de vraag niet positief is - nul en oneindig liegen allebei bij sorteren.
	column dekking_weken
		dataType: double
		formatString: 0.0
		lineageTag: 8c93ceb2-5b56-42a5-a6fa-e7144c5ed909
		summarizeBy: none
		sourceColumn: dekking_weken

	/// Niet leverbaar / Onder kritisch / Let op / OK, op effectieve voorraad tegen kritische_voorraad - dezelfde drempels als de ERP-voorraadpagina.
	column voorraadstatus
		dataType: string
		lineageTag: 86d96412-ad3f-4acc-bcd3-9de8e5109938
		summarizeBy: none
		sourceColumn: voorraadstatus

	/// Peildatum + dekking in dagen, alleen binnen de uitverkoop-horizon.
	column verwachte_uitverkoopdatum
		dataType: dateTime
		formatString: Long Date
		lineageTag: 71916342-d3e6-43df-97a6-137347db9b9f
		summarizeBy: none
		sourceColumn: verwachte_uitverkoopdatum

		annotation UnderlyingDateTimeDataType = Date

	/// Openstaande inkoopwaarde in euro's, uit inkoop_regel.prijs op verzonden open orders. Het oude scraper-veld was een flessenaantal zonder euro; dit is echte inkoopwaarde en via stg_inkoop_db ook naar besteldatum te verouderen.
	column open_inkoopwaarde
		dataType: double
		lineageTag: 1ceee35c-4bcf-482c-b740-2f347c4141dc
		summarizeBy: sum
		sourceColumn: open_inkoopwaarde

	/// Zelfde wijnsoort-label als op fct_sales, voor product- en bestellijst-doorsnijdingen.
	column wijnsoort
		dataType: string
		lineageTag: 1ee21999-0aa7-4bf6-bf07-bc4dc0452d41
		summarizeBy: none
		sourceColumn: wijnsoort

	/// GCD van alle historische inkoopregel-hoeveelheden per product. Uitdrukkelijk NIET moq: het ERP-veld bestaat maar is nooit ingevuld; dit is waargenomen gedrag, geen contractueel minimum.
	column waargenomen_bestelveelvoud
		dataType: int64
		isHidden
		lineageTag: 470b34ed-acec-4a0f-870f-35fcbe61ad5d
		summarizeBy: none
		sourceColumn: waargenomen_bestelveelvoud

	/// Aantal historische inkoopregels achter waargenomen_bestelveelvoud; < 3 = dun bewijs.
	column n_inkoopregels
		dataType: int64
		isHidden
		lineageTag: 492ad7cd-1072-4c0e-aea6-76378569be82
		summarizeBy: none
		sourceColumn: n_inkoopregels

	/// Kleinste ooit ingekochte hoeveelheid (inkoop_regel, geannuleerde orders uitgesloten). Metgezel van waargenomen_bestelveelvoud.
	column kleinste_inkoop
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: c47da23c-064b-4d76-ae31-6298c567b3f1
		summarizeBy: none
		sourceColumn: kleinste_inkoop

		annotation SummarizationSetBy = Automatic

	/// Contractueel minimum aantal flessen per bestelling bij deze leverancier (ERP-leverancierspagina). Geldt per bestelling, niet per product.
	column leverancier_min_flessen
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 9f6c6232-c508-4e87-80ba-b6cec4339d9f
		summarizeBy: none
		sourceColumn: leverancier_min_flessen

		annotation SummarizationSetBy = Automatic

	/// Contractueel minimum aantal pallets per bestelling bij deze leverancier (ERP-leverancierspagina).
	column leverancier_min_pallets
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 0eac25f6-af59-4f70-b8e0-e3bd659bc04b
		summarizeBy: none
		sourceColumn: leverancier_min_pallets

		annotation SummarizationSetBy = Automatic

	/// Contractueel minimum orderbedrag bij deze leverancier (ERP-leverancierspagina); slechts 6 van 95 leveranciers vullen dit.
	column leverancier_min_bedrag
		dataType: double
		isHidden
		lineageTag: 3ef0dd6c-a70d-42d7-a95b-37a95fa70697
		summarizeBy: none
		sourceColumn: leverancier_min_bedrag

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Winsorised 12-weeks vraag (flessen/week): de uitbijterweek gedropt volgens de backtest-winnaar (scripts/backtest_forecast.py, volume-gewogen MAE 275,39). Sinds 2026-08-20 de hoofddefinitie van vraag; dekking_weken en verwachte_uitverkoopdatum rekenen hierop. gem_per_week_12w is de ongecorrigeerde rate en wijkt bewust af.
	column vraag_per_week
		dataType: double
		formatString: 0.00
		lineageTag: e9bbacac-87a2-4956-9907-0bd69513fbd8
		summarizeBy: sum
		sourceColumn: vraag_per_week

	/// 'incidenteel' = geen voorspelbaar vraagpatroon (hooguit 1 order ooit, of 1 klant met hooguit 4 orders). Rapporten tonen dan een streepje in plaats van een verzonnen getal.
	column vraag_status
		dataType: string
		isHidden
		lineageTag: 78a0ac43-ca23-402a-87df-9821347ab7e2
		summarizeBy: none
		sourceColumn: vraag_status

	/// True wanneer de topweek uit de rate is gedropt - de 12-weeks vraag werd door een uitbijterweek gedomineerd.
	column vraag_is_gewinsoriseerd
		dataType: boolean
		isHidden
		lineageTag: 720a3b96-1590-4fb7-93f7-7fff527516ce
		summarizeBy: none
		sourceColumn: vraag_is_gewinsoriseerd

	partition fct_voorraad = m
		mode: import
		source =
				let
				  Source = PostgreSQL.Database("ep-soft-salad-agt3f5p2.c-2.eu-central-1.aws.neon.tech:5432", "neondb"),
				  #"Navigation 1" = Source{[Schema = "marts", Item = "fct_voorraad_db"]}[Data],
				  // product_id arrives as Int64 from fct_voorraad_db; cast to text so the
				  // relationship to dim_product still resolves and so the DAX equality with
				  // fct_klant_product[product_id] still matches — both sides are then text.
				  // dim_product stays on the scraper-sourced mart (string product_id).
				  // Remove this step when dim_product also moves to the _db source.
				  #"Changed Type" = Table.TransformColumnTypes(#"Navigation 1", {{"product_id", type text}})
				in
				  #"Changed Type"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

