table fct_sales
	lineageTag: 0736954c-b332-4d10-8784-40996fcd8a71

	measure Omzet = CALCULATE(SUM(fct_sales[regel_totaal]), fct_sales[is_revenue] = TRUE())
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		lineageTag: cc8a5479-ac98-452b-8c8e-998e531856b3

	measure Flessen = CALCULATE(SUM(fct_sales[aantal]), fct_sales[is_stock_movement] = TRUE())
		formatString: #,0
		lineageTag: baf46d01-4d64-41b6-a9f3-6a8c61ab84e5

	measure Orders = CALCULATE(DISTINCTCOUNT(fct_sales[ordernummer]), fct_sales[is_revenue] = TRUE())
		formatString: 0.00
		lineageTag: 191adde1-6c67-43a2-a5a0-e20321e6d8f7

	measure 'Klanten met omzet' = CALCULATE(DISTINCTCOUNT(fct_sales[klant_id]), fct_sales[is_revenue] = TRUE())
		formatString: 0
		lineageTag: 745014f1-68ad-43d2-b904-3f0a528715fc

	measure 'Gem. orderwaarde' = DIVIDE([Omzet], [Orders])
		formatString: "€"\ #,0;-"€"\ #,0;"€"\ #,0
		lineageTag: 5ec75913-f37b-453d-9501-fd841c858e3d

	measure 'Omzet vorig jaar' = CALCULATE([Omzet], SAMEPERIODLASTYEAR(dim_date[datum]))
		lineageTag: c9e443e4-01b8-42d3-9e80-73cd102aed45

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Omzet groei %' = DIVIDE([Omzet] - [Omzet vorig jaar], [Omzet vorig jaar])
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 9939e1c9-df73-4bd8-a973-4849b7fe7855

	column sales_line_id
		dataType: string
		lineageTag: f8912b86-3230-4886-a2ec-28963137994a
		summarizeBy: none
		sourceColumn: sales_line_id

		annotation SummarizationSetBy = Automatic

	column ordernummer
		dataType: int64
		formatString: 0
		lineageTag: 94377121-72a7-43f8-8723-f3dc720b87a3
		summarizeBy: sum
		sourceColumn: ordernummer

		annotation SummarizationSetBy = Automatic

	column order_datum
		dataType: dateTime
		formatString: Long Date
		lineageTag: df430ab2-e520-499f-ad45-426eb0994842
		summarizeBy: none
		sourceColumn: order_datum

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column klant_id
		dataType: int64
		formatString: 0
		lineageTag: d198e1e6-49f4-433b-9206-5bbe88d7a68e
		summarizeBy: none
		sourceColumn: klant_id

		annotation SummarizationSetBy = Automatic

	column product_id
		dataType: string
		lineageTag: 450e96cd-b810-45cf-9683-36f474600f1b
		summarizeBy: none
		sourceColumn: product_id

		annotation SummarizationSetBy = Automatic

	column product_naam
		dataType: string
		lineageTag: 340e4226-40b8-440a-8f7a-14ee5ace3b09
		summarizeBy: none
		sourceColumn: product_naam

		annotation SummarizationSetBy = Automatic

	column order_type
		dataType: string
		lineageTag: dcc412d1-6b40-4f80-8be7-b6e02e57dfcc
		summarizeBy: none
		sourceColumn: order_type

		annotation SummarizationSetBy = Automatic

	column aantal
		dataType: int64
		formatString: 0
		lineageTag: e816e218-3b09-42e1-b4bd-549c1dbe96d1
		summarizeBy: sum
		sourceColumn: aantal

		annotation SummarizationSetBy = Automatic

	column stukprijs
		dataType: double
		lineageTag: 196e7912-3387-4db7-bb0a-098e9ccd2722
		summarizeBy: sum
		sourceColumn: stukprijs

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column btw_pct
		dataType: int64
		lineageTag: 5b668f76-0009-4094-8ba0-ed53029aab63
		summarizeBy: sum
		sourceColumn: btw_pct

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column regel_totaal
		dataType: double
		lineageTag: e59ea4ec-d56c-447c-ad7e-8779f6795bed
		summarizeBy: sum
		sourceColumn: regel_totaal

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column is_verkocht
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 9bd96cb9-c6f4-4370-9ea8-d1f80493ca3d
		summarizeBy: none
		sourceColumn: is_verkocht

		annotation SummarizationSetBy = Automatic

	column is_revenue
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: f7539f35-d9e5-4ff2-adc0-97f6b619673a
		summarizeBy: none
		sourceColumn: is_revenue

		annotation SummarizationSetBy = Automatic

	column is_stock_movement
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 6473a477-d091-4083-9ae9-9a86b2e3abbc
		summarizeBy: none
		sourceColumn: is_stock_movement

		annotation SummarizationSetBy = Automatic

	column product_unmatched
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 843f7045-5b56-4ac1-8897-9d80340ee20b
		summarizeBy: none
		sourceColumn: product_unmatched

		annotation SummarizationSetBy = Automatic

	column product_naam_ambiguous
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: f330d642-8742-4c8d-a29e-3e2a19bc2b39
		summarizeBy: none
		sourceColumn: product_naam_ambiguous

		annotation SummarizationSetBy = Automatic

	column extracted_at
		dataType: dateTime
		formatString: General Date
		lineageTag: 05365bfc-96c1-41c6-8b83-d3fa800f8272
		summarizeBy: none
		sourceColumn: extracted_at

		annotation SummarizationSetBy = Automatic

	column regel_id
		dataType: int64
		formatString: 0
		lineageTag: 957d6ef2-e8a4-45f4-b67e-0321ad118418
		summarizeBy: sum
		sourceColumn: regel_id

		annotation SummarizationSetBy = Automatic

	column magazijn_id
		dataType: int64
		formatString: 0
		lineageTag: 86e1735f-cdfd-4be0-bf1f-1a4e4c6d863e
		summarizeBy: sum
		sourceColumn: magazijn_id

		annotation SummarizationSetBy = Automatic

	column status_inferred
		dataType: string
		lineageTag: 85b1bc29-bd17-4f92-a8e2-d700c455a5d4
		summarizeBy: none
		sourceColumn: status_inferred

		annotation SummarizationSetBy = Automatic

	column korting
		dataType: double
		lineageTag: e3a660f9-fc72-46fb-9aaa-4483ef1163c4
		summarizeBy: sum
		sourceColumn: korting

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column korting_percentage
		dataType: double
		lineageTag: a1fd69b3-2e73-4445-ad8d-51fcdf9add35
		summarizeBy: sum
		sourceColumn: korting_percentage

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column kostprijs
		dataType: double
		lineageTag: b49e911e-7d28-4aff-9e17-e1766a5f18e4
		summarizeBy: sum
		sourceColumn: kostprijs

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column regel_totaal_bruto
		dataType: double
		lineageTag: 5c015805-ff1d-4566-9d07-31c70a324ae0
		summarizeBy: sum
		sourceColumn: regel_totaal_bruto

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column is_sample
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 470e6684-9e4f-4d19-878e-16acf6506424
		summarizeBy: none
		sourceColumn: is_sample

		annotation SummarizationSetBy = Automatic

	partition fct_sales = m
		mode: import
		source =
				let
				  Source = PostgreSQL.Database("ep-soft-salad-agt3f5p2.c-2.eu-central-1.aws.neon.tech:5432", "neondb"),
				  #"Navigation 1" = Source{[Schema = "marts", Item = "fct_sales_db"]}[Data],
				  // product_id arrives as Int64 from fct_sales_db; cast to text so the
				  // relationship to dim_product still resolves — dim_product stays on
				  // the scraper-sourced mart (string product_id) until the stock-quantity
				  // gap in dim_product_db/fct_voorraad_db is resolved. Remove this step
				  // when dim_product also moves to the _db source.
				  #"Changed Type" = Table.TransformColumnTypes(#"Navigation 1", {{"product_id", type text}})
				in
				  #"Changed Type"

	annotation PBI_ResultType = Table

